package sbnz.integracija;

import sbnz.integracija.example.model.User;
import sbnz.integracija.example.model.Reservation;
import org.apache.commons.lang.time.DateUtils
import java.util.*

agenda-group "kategorije"
rule "GOLD"
	lock-on-active true
	salience 50
	when 
		$user: User($korisnikId : id)
		$rezervacija : Reservation()
		$rezervacije : List() from collect ( Reservation(user == $korisnikId, status == "ZAVRSEN",
		$fromDate : fromDate,
		$pomerenDatum: DateUtils.addMonths(new Date(), -12),
		eval($pomerenDatum.before($fromDate))) )
        $total : Number(intValue >= 500) from accumulate(
			 $s: Reservation () from $rezervacije,
	         init( int intValue = 0; ),
	         action( intValue += $s.getPrice(); ),
	         result( intValue )
		)
		eval($rezervacije.size()>4)
	then
		System.out.println("Ovaj korisnik ima :" + $rezervacije.size() + " rezervacija ukupne cene: " +$total + " i dodeljen mu je GOLD status" );
		modify ($user) { setMedal("GOLD"); }		
		drools.halt();
end
rule "SILVER"
	lock-on-active true
	salience 20
	when 
		$user: User($korisnikId : id, 
		$fromDate : registrationDate,
		$pomerenDatum: DateUtils.addMonths(new Date(), -6),
		eval($pomerenDatum.after($fromDate)))
		$rezervacija : Reservation()
		$rezervacije : List() from collect ( Reservation(user == $korisnikId, status == "ZAVRSEN") )
        $total : Number(intValue >= 500) from accumulate(
			 $s: Reservation () from $rezervacije,
	         init( int intValue = 0; ),
	         action( intValue += $s.getPrice(); ),
	         result( intValue )
		)
		eval($rezervacije.size()>1)
	then
		System.out.println("Ovaj korisnik ima :" + $rezervacije.size() + " rezervacija ukupne cene: " +$total + " i dodeljen mu je SILVER status" );
		modify ($user) { setMedal("SILVER"); }		
		drools.halt();
end

rule "BRONZE"
	lock-on-active true
	salience -100
	when 
		$user: User()
	then
		modify ($user) { setMedal("BRONZE"); }		
		drools.halt();
end