package sbnz.integracija;

import sbnz.integracija.example.model.User;
import sbnz.integracija.example.model.Reservation;
import org.apache.commons.lang.time.DateUtils
import java.util.*

agenda-group "kategorije"

rule "BRONZE"
	salience 50
	when 
		$user: User()
	then
		modify ($user) { setMedal("BRONZE"); }		
end

rule "SILVER"
	salience 20
	when 
		$user: User($korisnikId : id, 
		medal == "BRONZE",
		$fromDate : registrationDate,
		$pomerenDatum: DateUtils.addMonths(new Date(), -6),
		eval($pomerenDatum.after($fromDate)))
		$rezervacija : Reservation()
		$rezervacije : List() from collect ( Reservation(user == $korisnikId, status == "ZAVRSEN") )
        Number(intValue >= 500) from accumulate(
			 $s: Reservation ($p : price) from $rezervacije,
	         sum($p)
		)
		eval($rezervacije.size()>1)
	then
		System.out.println("Ovaj korisnik ima " + $rezervacije.size() + " i dodeljen mu je SILVER status" );
		modify ($user) { setMedal("SILVER"); }		
end

rule "GOLD"
	salience 10
	when 
		$user: User($korisnikId : id,medal == "SILVER")
		$rezervacija : Reservation()
		$rezervacije : List() from collect ( Reservation(user == $korisnikId, status == "ZAVRSEN",
		$fromDate : fromDate,
		$pomerenDatum: DateUtils.addMonths(new Date(), -12),
		eval($pomerenDatum.before($fromDate))) )
        Number(intValue >= 500) from accumulate(
			 $s: Reservation ($p : price) from $rezervacije,
	         sum($p)
		)
		eval($rezervacije.size()>4)
	then
		System.out.println("Ovaj korisnik ima " + $rezervacije.size() + " i dodeljen mu je GOLD status" );
		modify ($user) { setMedal("GOLD"); }		
end