package sbnz.integracija;

import sbnz.integracija.example.facts.Item;
import sbnz.integracija.example.facts.User;
import sbnz.integracija.example.facts.Reservation;
import org.apache.commons.lang.time.DateUtils
import java.util.*

rule "Ako korisnik zeli da produži rentiranje dobija dodatni popust od 10%"
	agenda-group "popusti"
	lock-on-active true
	salience -100
	when 
		$new : Reservation($korisnikId : user,status == 2, $automobilId : car)
	then
		System.out.println("Produzavanje");
		$new.setPrice($new.getPrice()*0.9);
		update($new);
		drools.halt();
end

rule "Popust od 40% za korisnika koji zeli da rentira automobil koji je rentirao u prethodnih mesec dana"
	agenda-group "popusti"
	lock-on-active true
	salience 112
	when 
		$new : Reservation($korisnikId : user,status == 0, $automobilId : car)
        $reservations : List() from collect ( Reservation($datumPocetka : fromDate,
        car == $automobilId,
        user == $korisnikId,
        status == 1,
        $pomeren: DateUtils.addDays(new Date(), -30),
        eval($pomeren.before(fromDate))       
        ) 
        )
        eval ( $reservations.size() >= 1 )
	then
		System.out.println("Velicina : "+$reservations.size() + ",KorisnikId = " + $korisnikId + ",NAJVECI");
		$new.setPrice($new.getPrice()*0.6);
		update($new);
		drools.halt();
		
end

rule "Popust od 30% ukoliko je u proteklih mesec dana rentirao automobil"
	agenda-group "popusti"
	lock-on-active true
	salience 80
	when 
		$new : Reservation($korisnikId : user,status == 0)
        $reservations : List() from collect ( Reservation($datumPocetka : fromDate,
        user == $korisnikId,
        status == 1,
        $pomeren: DateUtils.addDays(new Date(), -30),
        eval($pomeren.before(fromDate))
        ) )
        eval ( $reservations.size() >= 1 )
	then
		System.out.println("Velicina : "+$reservations.size() + ",KorisnikId = " + $korisnikId + ",Stara cena: "+$new.getPrice());
		$new.setPrice($new.getPrice()*0.7);
		update($new);
		drools.halt();
		
end

rule "Popust od 20% ukoliko korisnik zakaže rentiranje mesec dana ranije"
	agenda-group "popusti"
	lock-on-active true
	salience 60
	when 
		$i: Reservation($datumPocetka : fromDate, status == 0,
		$pomeren: DateUtils.addDays(new Date(), 30),
        eval($pomeren.before(fromDate))
		)
	then
		System.out.println("Stara cena : "+$i.getPrice());
		$i.setPrice($i.getPrice()*0.8);
		update($i);
		drools.halt();
end
