package sbnz.integracija;

import sbnz.integracija.example.model.*;
import org.apache.commons.lang.time.DateUtils
import java.util.*

agenda-group "pretraga"
rule "OPEL"
	no-loop
	salience($dp.priority)

	
	when
		$predlog: Search($uslovi: uslovi, $opelUslovi: opelUslovi )
		$dp: Priority($p: priority >= 3) from accumulate(
			$s: Characteristic (
				name memberOf $opelUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(6);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("OPEL");}
		System.out.println("Model za vas je OPEL");
end
rule "CITROEN"
	no-loop
	salience($dp.priority)

	when
		$predlog: Search($uslovi: uslovi, $citroenUslovi : citroenUslovi)
		$dp: Priority($p: priority >= 3) from accumulate(
			$s: Characteristic (
				name memberOf $citroenUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(4);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("CITROEN");}
		System.out.println("Model za vas je CITROEN");
end
rule "FORD"
	no-loop
	salience($dp.priority)

	when
		$predlog: Search($uslovi: uslovi, $fordUslovi : fordUslovi)
		$dp: Priority($p: priority >= 3) from accumulate(
			$s: Characteristic (
				name memberOf $fordUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(5);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("FORD");}
		System.out.println("Model za vas je FORD");
end
rule "BMW"
	no-loop
	salience($dp.priority + 10)

	when
		$predlog: Search($uslovi: uslovi, $bmwUslovi : bmwUslovi)
		$dp: Priority($p: priority == 5) from accumulate(
			$s: Characteristic (
				name memberOf $bmwUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(10);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("BMW");}
		System.out.println("Model za vas je BMW");
end
rule "MERCEDES"
	no-loop
	salience($dp.priority + 10)

	when
		$predlog: Search($uslovi: uslovi, $mercedesUslovi : mercedesUslovi)
		$dp: Priority($p: priority == 5) from accumulate(
			$s: Characteristic (
				name memberOf $mercedesUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(10);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("MERCEDES");}
		System.out.println("Model za vas je MERCEDES");
end
rule "VOLVO"
	no-loop
	salience($dp.priority + 10)

	when
		$predlog: Search($uslovi: uslovi, $volvoUslovi : volvoUslovi)
		$dp: Priority($p: priority == 5) from accumulate(
			$s: Characteristic (
				name memberOf $volvoUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(10);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("VOLVO");}
		System.out.println("Model za vas je VOLVO");
end

rule "FERARI"
	no-loop
	salience($dp.priority + 50 + $dpSpec.priority)

	when
		$predlog: Search($uslovi: uslovi,$spec : specificniUslovi, $ferariUslovi : ferariUslovi, $ferariSpecUslovi : ferariSpecUslovi)
		$dp: Priority($p: priority >= 1) from accumulate(
			$s: Characteristic (
				name memberOf $ferariUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(2);),
			action($priority.addModel();),
			result($priority)
		)
		$dpSpec: Priority($pSpec: priority >= 1) from accumulate(
			$s: Characteristic (
				name memberOf $ferariSpecUslovi
			) from $spec,
			init(Priority $priority = new Priority(3);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("FERARI");}
		System.out.println("Model za vas je FERARI");
end
rule "BUGATI"
	no-loop
	salience($dp.priority + 50 + $dpSpec.priority)

	when
		$predlog: Search($uslovi: uslovi,$spec : specificniUslovi, $bugatiUslovi : bugatiUslovi, $bugatiSpecUslovi : bugatiSpecUslovi)
		$dp: Priority($p: priority >= 1) from accumulate(
			$s: Characteristic (
				name memberOf $bugatiUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(2);),
			action($priority.addModel();),
			result($priority)
		)
		$dpSpec: Priority($pSpec: priority >= 1) from accumulate(
			$s: Characteristic (
				name memberOf $bugatiSpecUslovi
			) from $spec,
			init(Priority $priority = new Priority(3);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("BUGATI");}
		System.out.println("Model za vas je BUGATI");
end

rule "BENTLI"
	no-loop
	salience($dp.priority + 50 + $dpSpec.priority)

	when
		$predlog: Search($uslovi: uslovi,$spec : specificniUslovi, $bentliUslovi: bentliUslovi, $bentliSpecUslovi : bentliSpecUslovi)
		$dp: Priority($p: priority >= 1) from accumulate(
			$s: Characteristic (
				name memberOf $bentliUslovi
			) from $uslovi,
			init(Priority $priority = new Priority(2);),
			action($priority.addModel();),
			result($priority)
		)
		$dpSpec: Priority($pSpec: priority >= 1) from accumulate(
			$s: Characteristic (
				name memberOf $bentliSpecUslovi
			) from $spec,
			init(Priority $priority = new Priority(3);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("BENTLI");}
		System.out.println("Model za vas je BENTLI");
end
