package sbnz.integracija;

import sbnz.integracija.example.model.*;
import org.apache.commons.lang.time.DateUtils
import java.util.*

agenda-group "pretraga"
rule "OPEL"
	no-loop
	salience($dp.priority)

	
	when
		$predlog: Search($uslovi: uslovi)
		$dp: Priority($p: priority >= 3) from accumulate(
			$s: Characteristic (
				name == "Germany" ||
				name == "Small Car" ||
				name == "Petrol" ||
				name == "Manual gearbox" ||
				name == "ABS" ||
				name == "Full leather"
			) from $uslovi,
			init(Priority $priority = new Priority(6);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("OPEL");}
		System.out.println("Model za vas je OPEL");
end
rule "CITROEN"
	no-loop
	salience($dp.priority)

	when
		$predlog: Search($uslovi: uslovi)
		$dp: Priority($p: priority >= 3) from accumulate(
			$s: Characteristic (
				name == "France" ||
				name == "Saloon" ||
				name == "Automatic transmission" ||
				name == "Navigation system"
			) from $uslovi,
			init(Priority $priority = new Priority(4);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("CITROEN");}
		System.out.println("Model za vas je CITROEN");
end
rule "FORD"
	no-loop
	salience($dp.priority)

	when
		$predlog: Search($uslovi: uslovi)
		$dp: Priority($p: priority >= 3) from accumulate(
			$s: Characteristic (
				name == "USA" ||
				name == "SUV" ||
				name == "LPG" ||
				name == "ESP" ||
				name == "Manual gearbox" 
			) from $uslovi,
			init(Priority $priority = new Priority(5);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("FORD");}
		System.out.println("Model za vas je FORD");
end
rule "BMW"
	no-loop
	salience($dp.priority + 10)

	when
		$predlog: Search($uslovi: uslovi)
		$dp: Priority($p: priority == 5) from accumulate(
			$s: Characteristic (
				name == "Germany" ||
				name == "SUV" ||
				name == "Petrol" ||
				name == "Automatic transmission" ||
				name == "360 camera" 
			) from $uslovi,
			init(Priority $priority = new Priority(10);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("BMW");}
		System.out.println("Model za vas je BMW");
end
rule "MERCEDES"
	no-loop
	salience($dp.priority + 10)

	when
		$predlog: Search($uslovi: uslovi)
		$dp: Priority($p: priority == 5) from accumulate(
			$s: Characteristic (
				name == "Germany" ||
				name == "Saloon" ||
				name == "Petrol" ||
				name == "Automatic transmission" ||
				name == "Sport seats" 
			) from $uslovi,
			init(Priority $priority = new Priority(10);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("MERCEDES");}
		System.out.println("Model za vas je MERCEDES");
end
rule "VOLVO"
	no-loop
	salience($dp.priority + 10)

	when
		$predlog: Search($uslovi: uslovi)
		$dp: Priority($p: priority == 5) from accumulate(
			$s: Characteristic (
				name == "Sweden" ||
				name == "SUV" ||
				name == "Petrol" ||
				name == "Automatic transmission" ||
				name == "LED headlights" 
			) from $uslovi,
			init(Priority $priority = new Priority(10);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("VOLVO");}
		System.out.println("Model za vas je VOLVO");
end

rule "FERARI"
	no-loop
	salience($dp.priority + 50 + $dpSpec.priority)

	when
		$predlog: Search($uslovi: uslovi,$spec : specificniUslovi)
		$dp: Priority($p: priority >= 1) from accumulate(
			$s: Characteristic (
				name == "Italy" ||
				name == "Coupe" 
			) from $uslovi,
			init(Priority $priority = new Priority(2);),
			action($priority.addModel();),
			result($priority)
		)
		$dpSpec: Priority($pSpec: priority >= 1) from accumulate(
			$s: Characteristic (
				name == "Night vision assist" ||
				name == "Heated streering wheel" || 
				name == "Bi-xenon headlights" 
			) from $spec,
			init(Priority $priority = new Priority(3);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("FERARI");}
		System.out.println("Model za vas je FERARI");
end
rule "BUGATI"
	no-loop
	salience($dp.priority + 50 + $dpSpec.priority)

	when
		$predlog: Search($uslovi: uslovi,$spec : specificniUslovi)
		$dp: Priority($p: priority >= 1) from accumulate(
			$s: Characteristic (
				name == "France" ||
				name == "Cabriolet" 
			) from $uslovi,
			init(Priority $priority = new Priority(2);),
			action($priority.addModel();),
			result($priority)
		)
		$dpSpec: Priority($pSpec: priority >= 1) from accumulate(
			$s: Characteristic (
				name == "Sports suspension" ||
				name == "Hands-free" || 
				name == "Digital cockpit" 
			) from $spec,
			init(Priority $priority = new Priority(3);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("BUGATI");}
		System.out.println("Model za vas je BUGATI");
end

rule "BENTLI"
	no-loop
	salience($dp.priority + 50 + $dpSpec.priority)

	when
		$predlog: Search($uslovi: uslovi,$spec : specificniUslovi)
		$dp: Priority($p: priority >= 1) from accumulate(
			$s: Characteristic (
				name == "United Kingdom" ||
				name == "Saloon" 
			) from $uslovi,
			init(Priority $priority = new Priority(2);),
			action($priority.addModel();),
			result($priority)
		)
		$dpSpec: Priority($pSpec: priority >= 1) from accumulate(
			$s: Characteristic (
				name == "Voice control" ||
				name == "ISOFIX" || 
				name == "Start-stop system" 
			) from $spec,
			init(Priority $priority = new Priority(3);),
			action($priority.addModel();),
			result($priority)
		)
	then
		modify($predlog){setModel("BENTLI");}
		System.out.println("Model za vas je BENTLI");
end
