package sbnz.integracija;

import sbnz.integracija.example.facts.Item;
import sbnz.integracija.example.facts.User;
import sbnz.integracija.example.facts.Reservation;
import org.apache.commons.lang.time.DateUtils
import java.util.*

/*
rule "Classify Item - High Range"
    when
        $i: Item( cost > 300, category == Category.NA )
    then
        $i.setCategory(Item.Category.HIGH_RANGE);
        update($i);
end*/

rule "Popust od 20% ukoliko korisnik zakaže rentiranje mesec dana ranije"
	lock-on-active true
	when 
		$i: Reservation($datumPocetka : fromDate,
		$pomeren: DateUtils.addDays(new Date(), 30),
        eval($pomeren.before(fromDate))
		)
	then
		$i.setPrice($i.getPrice()*0.8);
		update($i);
		
end